staylor/react-helmet-async

package-lock.json, package.json, src/index.js
This will generally run faster and compare elements
in children correctly and reliably.
In development it's also possible to run into circular
references on element comparisons in some setups, which
deep-equal doesn't handle gracefully.
For a readme on react-fast-compare see: https://github.com/FormidableLabs/react-fast-compare
=> Replace deep-equal in Helmet#sCU with react-fast-compare

src/Dispatcher.js, src/utils.js
I eliminated two occurrences of `Object.assign` by using the object spread syntax instead. The latter one is compiled away by babel.
See #18 for details.
=> FIXES #18: replace Object.assign with spread op

__tests__/__snapshots__/fragment.test.js.snap, __tests__/fragment.test.js, src/constants.js, src/index.js
Makes the following work:
```
<Helmet>
<Fragment>
<title>Foo</title>
<Fragment>
<title>Bar</title>
<Fragment>
<title>Baz</title>
</Fragment>
</Fragment>
</Fragment>
</Helmet>
```
`<title>` will equal "Baz"
Fixes #20
=> Support Fragment within Helmet

src/Context.js, src/Provider.js, src/index.js
I have this special use case with two `react-helmet-async` installed in two projects. Let's say Project A and Project B.
And the `Context.js` module is causing an error:
```
: Uncaught TypeError: Cannot read property 'add' of undefined
```
The problem here is `Helmet` is importing `Context.js` from `react-helmet-async` in Project A. And `Provider` is importing `Context.js` from `react-helmet-async` in Project B. They're two different `Context`.
This pull request move `Context` into `Provider` module so `Helmet` shares the same context with `Provider` in my use case.
=> Move Context to Provider

.babelrc, package-lock.json, package.json, src/Provider.js
simplifies `.babelrc` and strips `propTypes` when building
=> update all Babel deps

index.d.ts
this config is not standard and forces people to use it in order to compile typescript projects
=> fix: 🐛 typescript typings disable esModuleInterop enforcement

package-lock.json, package.json
This commit updates Jest to 24.5 and replaces the now deprecated
setupTestFrameworkScriptFile with setupFilesAfterEnv.
This update also resolves a raft of vulnerabilities stemming from Jest's
dependencies.
=> Update to Jest 24.5.0

index.d.ts
rewind etc are not valid for this library, forking the react-helmet types into this project
fixes #61
=> Copies react-helmet types across so incorrect types can be removed

package.json
Closes #109
Contrary to #107, does NOT upgrade internal tests to React 17 yet - it just gets rid of the warning shown when react-helmet-async is used in React 17 environment.
=> feat: allow React 17 in peerDependencies

README.md, __tests__/server/server.test.js, src/constants.js, src/index.js, src/server.js, src/utils.js
Addresses #23, allowing for prioritization of certain HTML tags towards the begining of the `<head>`. This only runs on the server, but is respected on the client. 
See see [this section of the README](https://github.com/staylor/react-helmet-async/blob/dd030ab1b288abb5d1f1ac8ae120d2aec24bf766/README.md#prioritizing-tags-for-seo) for full details.
=> Prioritizes certain tags for SEO

README.md
Currently, points to https://github.com/staylor/react-helmet-async/blob/master/blob/master/src/constants.js
=> docs: fix link to seo constants

.circleci/config.yml, README.md, __tests__/server/__snapshots__/helmetData.test.js.snap, __tests__/server/helmetData.test.js, jest.config.js, src/HelmetData.js, src/Provider.js, src/index.js
This is useful for React Server Components, which do not yet support context. There is also debate on whether or not RSC server context should be used for this type of functionality. This will be immediately used by Hydrogen at Shopify: https://github.com/Shopify/hydrogen/issues/253
=> feat: add the ability to use `<Helmet>` without context

__tests__/server/__snapshots__/helmetData.test.js.snap, __tests__/server/helmetData.test.js, index.d.ts, src/HelmetData.js, src/index.js
Expose TypeScript types.
RSC cannot serialize methods and functions between the server and client, so we need to support recreating `HelmetData` with the serialized data from the server. This works because `HelmetData` itself is just a wrapper over a context object and an instances array. Those can be the same refs in memory for multiple HelmetData instances.
=> fix: make sure HelmetData uses the same context data under the hood

__tests__/server/helmetData.test.js, index.d.ts, jest.setup.js, src/HelmetData.js, src/Provider.js, src/index.js, src/utils.js
1. fix: move to a singleton for tracking `Helmet` instances 
This resolves an issue where multiple `HelmetProvider`s on the same
page don't know about each other.
2. fix: don't emit changes when the `helmetData` wrapper object changes 
This makes the context free environment behave like a context environment,
for example, the outer context could be destroyed and recreated, and emitting
changes isn't effected. `The helmetData` should behave the same.
=> Singleton instances

index.d.ts
In the TypeScript file, because there is `class HelmetData` and `interface HelmetData` and the name are exactly the same.
This means we are unable to import the type for `class HelmetData`. 
For example `import type {HelmetData} from 'react-helmet-async'` gives the interface type, not the class type). See it happening [here](https://github.com/Shopify/hydrogen/pull/596/files#diff-622e580245bf2de41f2923da321ac61875c9b37618d09d54c1916b0cb0e97209) and how we need to create new type to get around it.
This PR rename the interface type to make this less confusing.
=> rename HelmetData interface to HelmetServerState

index.d.ts, package.json
React 18 doesn't have any relevant breaking changes.
closes #163
closes #166
=> feat: support React 18

src/constants.js
https://html.spec.whatwg.org/multipage/semantics.html#standard-metadata-names
```
<meta name="generator" content="Docusaurus v2.0.0-rc.1">
```
This Meta tag doesn't need to be at the very top, but most frameworks implement it this way. 
It is very convenient to use DevTools and see which generator was used at the very top, it helps us know which tool a site is using without inspecting a long list of metadata
cc @justinph
=> feat: add "generator" as SEO priority meta

package.json, src/HelmetData.ts, src/Provider.tsx
=> fix: make context prop optional in Provider

src/Provider.tsx
When passing the provider as a type to a function it's currently not compatible with `ComponentType<{ children: ReactNode }>` as the props in the constructor is not accepting `children` when the component does. The prop types in the constructor should be the same as the component itself.
=> Added correct props type to provider constructor

package.json
react-dom is not strictly required by this library - it's not used in the source code directly, only in tests (which is covered by the dev dependency). We use react-helmet-async in expo-router (which works on any or all of iOS, Android, and web), and this peer dependency led to the following issue with the release of react@18.3.0 / react-dom@18.3.0: https://github.com/expo/expo/issues/28471#issuecomment-2080094893
=> fix: remove react-dom from peerDependencies

README.md
Resolves #211.
File extension was not updated during switch from JS to TS in: https://github.com/staylor/react-helmet-async/commit/44f4997f677aa326c3a9e1683b5a281333cafe55#diff-8fa4b52909f895e8cda060d2035234e0a42ca2c7d3f8f8de1b35a056537bf199
=> [docs] Fixes file path in `README.md`
